-- ============================================
-- BLACK INDEX: THE LEDGER (Database Schema)
-- Run this in Supabase SQL Editor
-- ============================================

-- 1. PROFILES (Warlords & Founders)
-- Extends Supabase Auth - stores seller/founder profiles
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade not null primary key,
  role text check (role in ('admin', 'founder', 'warlord')) default 'warlord',
  username text unique,
  stripe_connect_id text,
  full_name text,
  avatar_url text,
  
  -- The Vault (Escrow Logic) - all amounts in paise
  pending_balance bigint default 0,      -- Locked (T+30)
  withdrawable_balance bigint default 0, -- Cleared & Ready
  total_earnings bigint default 0,       -- All-time earnings
  
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 2. PRODUCTS (The Armoury)
-- Products listed on the Black Index
create table if not exists public.products (
  id uuid default gen_random_uuid() primary key,
  founder_id uuid references public.profiles(id) on delete cascade not null,
  name text not null,
  description text,
  logo_url text,
  website_url text not null,
  is_active boolean default true,
  
  -- Commission Config (Hybrid Model)
  -- Structure: { "type": "hybrid", "upfront_pct": 40, "recurring_pct": 15, "max_recurring_months": 12 }
  commission_config jsonb not null,
  
  -- Risk Management
  max_cac_limit bigint, -- Max bounty per user (in paise)
  webhook_secret text not null, -- HMAC Key for signature verification
  
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- 3. LINKS (The Spine)
-- Tracking links generated by Warlords
create table if not exists public.links (
  id uuid default gen_random_uuid() primary key,
  seller_id uuid references public.profiles(id) on delete cascade not null,
  product_id uuid references public.products(id) on delete cascade not null,
  slug text unique not null, -- e.g., 'blackindex.so/ref/aryan'
  
  clicks bigint default 0,
  unique_visitors bigint default 0,
  
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 4. TRANSACTIONS (Ledger Entries)
-- All financial activities
create table if not exists public.transactions (
  id uuid default gen_random_uuid() primary key,
  type text check (type in ('sale', 'refund', 'payout')) not null,
  status text check (status in ('pending', 'cleared', 'cancelled', 'paid')) default 'pending',
  
  product_id uuid references public.products(id) on delete set null,
  seller_id uuid references public.profiles(id) on delete set null,
  link_id uuid references public.links(id) on delete set null,
  
  -- Financials (in paise - smallest currency unit)
  sale_amount bigint not null,
  commission_amount bigint not null,
  platform_fee bigint not null,
  
  -- Attribution Data
  external_customer_id text, -- From Stripe/Razorpay
  external_transaction_id text unique, -- Idempotency key
  
  -- The Lock (T+30 days)
  payout_due_date timestamp with time zone,
  
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- 5. WEBHOOK LOGS (Audit Trail / Black Box)
-- Track all incoming webhook events
create table if not exists public.webhook_logs (
  id uuid default gen_random_uuid() primary key,
  product_id uuid references public.products(id) on delete set null,
  payload jsonb,
  status text check (status in ('success', 'failed', 'rejected')),
  error_message text,
  ip_address text,
  created_at timestamp with time zone default timezone('utc'::text, now())
);

-- ============================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================

-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.links enable row level security;
alter table public.transactions enable row level security;
alter table public.webhook_logs enable row level security;

-- PROFILES POLICIES
create policy "Users can view own profile" on profiles
  for select using (auth.uid() = id);

create policy "Users can update own profile" on profiles
  for update using (auth.uid() = id);

create policy "Enable insert for authenticated users only" on profiles
  for insert with check (auth.uid() = id);

-- PRODUCTS POLICIES
create policy "Anyone can view active products" on products
  for select using (is_active = true);

create policy "Founders can view own products" on products
  for select using (auth.uid() = founder_id);

create policy "Founders can insert own products" on products
  for insert with check (auth.uid() = founder_id);

create policy "Founders can update own products" on products
  for update using (auth.uid() = founder_id);

create policy "Founders can delete own products" on products
  for delete using (auth.uid() = founder_id);

-- LINKS POLICIES
create policy "Anyone can view links" on links
  for select using (true);

create policy "Sellers can create own links" on links
  for insert with check (auth.uid() = seller_id);

create policy "Sellers can update own links" on links
  for update using (auth.uid() = seller_id);

create policy "Sellers can delete own links" on links
  for delete using (auth.uid() = seller_id);

-- TRANSACTIONS POLICIES
create policy "Sellers can view own transactions" on transactions
  for select using (auth.uid() = seller_id);

-- Webhook logs are server-side only (service role)

-- ============================================
-- INDEXES FOR PERFORMANCE
-- ============================================

create index if not exists idx_profiles_username on profiles(username);
create index if not exists idx_products_founder on products(founder_id);
create index if not exists idx_products_active on products(is_active);
create index if not exists idx_links_seller on links(seller_id);
create index if not exists idx_links_product on links(product_id);
create index if not exists idx_links_slug on links(slug);
create index if not exists idx_transactions_seller on transactions(seller_id);
create index if not exists idx_transactions_status on transactions(status);
create index if not exists idx_transactions_payout_due on transactions(payout_due_date);

-- ============================================
-- TRIGGER: Auto-create profile on signup
-- ============================================

create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger when a new user signs up
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- ============================================
-- TRIGGER: Update updated_at timestamp
-- ============================================

create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$ language plpgsql;

create trigger update_profiles_updated_at
  before update on public.profiles
  for each row execute procedure public.update_updated_at_column();

create trigger update_products_updated_at
  before update on public.products
  for each row execute procedure public.update_updated_at_column();

-- ============================================
-- ENABLE REALTIME
-- ============================================

alter publication supabase_realtime add table transactions;
alter publication supabase_realtime add table links;
